apiVersion: v1
kind: Service
metadata:
  name: neo-cloudz-inference
  labels:
    app: neo-cloudz-inference
spec:
  selector:
    app: neo-cloudz-inference
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: ClusterIP
